// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjC4dS-lzAbuJHdVws_BUNVoEata_R8o',
    appId: '1:163654752472:web:c83c1b20412dfbfd789fad',
    messagingSenderId: '163654752472',
    projectId: 'mylmazos',
    authDomain: 'mylmazos.firebaseapp.com',
    databaseURL: 'https://mylmazos-default-rtdb.firebaseio.com',
    storageBucket: 'mylmazos.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1ulKxVh5KQejQSz4vAFxHvIla2XDFDoM',
    appId: '1:163654752472:android:c805174cf78c2d1f789fad',
    messagingSenderId: '163654752472',
    projectId: 'mylmazos',
    databaseURL: 'https://mylmazos-default-rtdb.firebaseio.com',
    storageBucket: 'mylmazos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkAZFNEons-8kNFWQgm0qbV3eb2OkAeTE',
    appId: '1:163654752472:ios:66673b807e8ed89d789fad',
    messagingSenderId: '163654752472',
    projectId: 'mylmazos',
    databaseURL: 'https://mylmazos-default-rtdb.firebaseio.com',
    storageBucket: 'mylmazos.firebasestorage.app',
    iosBundleId: 'com.example.mylDecks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkAZFNEons-8kNFWQgm0qbV3eb2OkAeTE',
    appId: '1:163654752472:ios:66673b807e8ed89d789fad',
    messagingSenderId: '163654752472',
    projectId: 'mylmazos',
    databaseURL: 'https://mylmazos-default-rtdb.firebaseio.com',
    storageBucket: 'mylmazos.firebasestorage.app',
    iosBundleId: 'com.example.mylDecks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVjC4dS-lzAbuJHdVws_BUNVoEata_R8o',
    appId: '1:163654752472:web:881bfd1bb5df3fbc789fad',
    messagingSenderId: '163654752472',
    projectId: 'mylmazos',
    authDomain: 'mylmazos.firebaseapp.com',
    databaseURL: 'https://mylmazos-default-rtdb.firebaseio.com',
    storageBucket: 'mylmazos.firebasestorage.app',
  );

}